---
- name: Configure lab
  hosts: lab
  become: true
  gather_facts: true
  vars_files:
    - vars.yml

  roles:
    - { role: base, tags: [base] }
    - { role: users, tags: [users] }
    - { role: storage, tags: [storage] }
    - { role: nvidia, tags: [nvidia] }
    - { role: docker, tags: [docker] }
    - { role: firewall, tags: [firewall] }
    - { role: conda, tags: [conda] }
    - { role: tools, tags: [tools] }
    - { role: llama_swap, tags: [llama_swap] }
